# Generated by Django 4.1.7 on 2023-03-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=200)),
                ('descriere', models.CharField(max_length=200)),
                ('ambalaj', models.CharField(choices=[('100g', '100g'), ('200g', '200g'), ('500g', '500g'), ('1000g', '1000g')], max_length=10)),
                ('pret', models.CharField(max_length=200)),
            ],
        ),
    ]
