# Generated by Django 4.1.7 on 2023-03-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produse',
            name='id_poza',
            field=models.CharField(blank=True, default=None, max_length=1500, null=True),
        ),
    ]
