# Generated by Django 4.1.7 on 2023-03-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proiect', '0002_produse_id_poza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=200)),
                ('descriere', models.CharField(max_length=200)),
                ('pret', models.CharField(max_length=200)),
                ('id_poza', models.CharField(blank=True, default=None, max_length=1500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='produse',
            name='pret',
        ),
        migrations.AlterField(
            model_name='produse',
            name='ambalaj',
            field=models.CharField(choices=[('100ml', '100ml'), ('200ml', '200ml'), ('50ml', '50ml'), ('250ml', '250ml')], max_length=10),
        ),
    ]
