# Generated by Django 4.1.3 on 2023-01-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subscription_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('movie', 'movie'), ('tv_series', 'tv_series')], max_length=10)),
                ('subtitle_languages', models.CharField(max_length=200)),
                ('length_minutes', models.IntegerField()),
                ('nr_of_episodes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('subscription_type', models.CharField(choices=[('individual', 'individual'), ('family', 'family'), ('premium', 'premium')], default='individual', max_length=10)),
                ('is_logged', models.BooleanField(default=False)),
            ],
        ),
    ]
