# Generated by Django 4.1.3 on 2023-01-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='nr_of_episodes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
