# Generated by Django 4.1.3 on 2023-01-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_alter_show_nr_of_episodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='poster',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
